language: python
sudo: false
dist: trusty
python:
    - "3.6"
addon:
    apt:
        packages:
            - flake8
            - coveralls
            - nose
before_install:
    - export PATH=$PATH:$PWD
    - pip install -r requirements.txt
    - pip install pytest
script:
    - pytest -v -s
sudo: false
notifications:
  email: false
