language: python
sudo: false
dist: trusty
python:
- '3.6'
addon:
  apt:
    packages:
    - flake8
    - coveralls
    - nose
before_install:
- export PATH=$PATH:$PWD
- pip install -r requirements.txt
- pip install pytest
script:
- pytest -v -s
notifications:
  email: false
env:
  global:
  - secure: GKif8Xhtht5FZya3aawiwXF6JtiRP34ybJTulYu1yciVVzIV/EGFSLYS1niSuVPPRpJbWFcgrbbdRHrbVUVolctKEOR5c6hj7U5PBVUSFcwDbaECj5q5UAyYXTOgPAwY+6eKvVWtUYQgaxMY+NZkbDgwZzOg8zQR3ht4R5gJDpCWlNJD3jFmvwC0HQ62PaUD8HlqyYkVUKChmIWNW8UxdKM3rg8tKi3ewFmNWC+lIzsgTwEHpN+Fy2LZKXSutkjFJISU4+hOPKiKMoc8lfM+oUSAvVxIMhZYYg79dK1V5aaYZw70l0Iaw8HwXeQSsGQLw3E7GpWdYb9LP0yYP74yx00VeVQyNDX2CMUh3Wcc5QXlN+5r1GhGRCyU7gL4Dk2lzNWyK7ogL5KJdshSOUguoCG6BxCNLhTe8PeChYekCxXjlOb7VvSpgCMJZedWgO0ObXyh/sIk85PLT3oy/mypHlRZaJ71I5WQJfg2v3LfVWrh1Tb+5n0f1dxIp5zb0KY5nqfsgCTQ8xz4A76zhCYlUzVC9WY38LEJt6+SomHR0QrUId/mUP0cVJmVb/D3IOwxsNS12RHUEhrN7L022lxowRJOHVfiXKOH6JpxinTkeGuPcahn1/oQ/lpVZnNzTZ+4F2aolYpHXufwUDJrUH166lnBx+SNwERVApiSzJmSagQ=
