language: python
sudo: false
dist: trusty
python:
    - "3.6"
addon:
    apt:
        packages:
            - flake8
            - coveralls
            - nose
before_install:
    - pip install -r requirements.txt
    - pip install pytest
script:
    - pytest
sudo: false
