#!/usr/bin/env python
import subprocess
import github
import yaml
import click
import sys
import textwrap
import json
import toml
import os


def pr(num):
    """Pulls down and checkout the branch of the pr.

    This will run the following commands in the terminal:
    "git remote add user git@github.com:user/repo",
    "git fetch user",
    "git checkout -b pr/num user/branch"

    Parameters
    ----------
    num : integer
        The number of the pull request.
    """
    process = subprocess.Popen("git remote -v", stdout=subprocess.PIPE)
    remotes = str(process.stdout.read())
    url = remotes.split(" ", 1)[0]  # gets the fetch url
    url = url.split("\\t", 1)[1]  # takes out extra info
    arguments = url.split(".com:")[1]  # gets just the username/repo.git
    arguments = arguments[:len(arguments) - 4]  # takes out ".git"
    username, repo = arguments.split("/")

    # gets token from config folder.
    try:
        with open(os.path.expanduser("~/.config/git-hub.yaml")) as stream:
            yaml_file = str(yaml.load(stream))
            token = yaml_file.split("=")[1].strip()

    except (IndexError, FileNotFoundError) as e:
        print(textwrap.dedent("""Needs an authentification token in: ~/.config/git-hub.yaml
            file simply says: token = abc123
            Visit https://help.github.com/articles/
            creating-a-personal-access-token-for-the-command-line/"""))
        sys.exit(1)

    # gets pr and runs command.
    try:
        g = github.Github(token)
        pr = g.get_user(username).get_repo(repo).get_pull(num)
        label = pr.head.label
        other_user, branch = label.split(":")
        remote_name = "\\n" + other_user + "\\t"
        if remote_name not in remotes:
            print(other_user)
            print(repo)
            p = subprocess.Popen(["git", "remote", "add", "{other_user}",
                                 f'git@github.com:{other_user}/{repo}'])
            p.communicate()
        p = subprocess.Popen(["git", "fetch", other_user],
                             stdout=subprocess.PIPE)
        p.stdout.read()
        subprocess.Popen(["git", "checkout", "-b",
                         f'pr/{num}', f'{other_user}/{branch}'])
        with open(".git_hub_cache", "w") as outfile:
            data = {"user": other_user, "pr": f'pr/{num}', "branch": branch}
            json.dump(data, outfile)

    except github.BadCredentialsException as e:
        print(e)
        print("The authentification token is not valid.")
        sys.exit(1)

    except github.UnknownObjectException as e:
        print(e)
        print(f'There is no pr with number {num}.')
        sys.exit(1)


def push():
    """Pushes changes back to a branch.

    This will run the following command:
    "git push user pr/num:branch"

    """
    try:
        with open(".git_hub_cache") as json_file:
            data = json.load(json_file)
            other_user = data["user"]
            pr = data["pr"]
            branch = data["branch"]
            p = subprocess.Popen(["git", "push", other_user,
                                 f'{pr}:{branch}'], stdout=subprocess.PIPE)
            p.stdout.read()
    except FileNotFoundError as e:
        print(e)
        print("This command must be used after git hub pr.")
        sys.exit(1)

def search(keyword):
    try:
        open_prs = False
        closed_prs = False
        f = open("./.git/pull-requests.toml","r")
        for line in f:
            num = line.split(" ",1)[0]
            pull = line.split(" ",1)[1]
            if keyword in pull:
                if not open_prs:
                    click.echo("OPEN pull requests")
                    open_prs = True
                click.echo('{0}  {1}'.format(num, pull[1:len(pull)-1]))

        #TODO - update to closed
        for line in f:
            num = line.split(" ",1)[0]
            pull = line.split(" ",1)[1]
            if keyword in pull:
                if not open_prs:
                    click.echo("CLOSED pull requests")
                    open_prs = True
                click.echo('{0}  {1}'.format(num, pull[1:len(pull)-1]))

        if not open_prs and not closed_prs:
            click.echo("Could not find '{0}' in pull requests. Update your pull requests with 'git hub sync' and try again.".format(keyword))
    except FileNotFoundError as e:
        #if pull-requests.toml hasnt been created yet calls sync and then reties to fetch
        sync()
        search(keyword)

def sync():
    # runs git and gets user and repo of current folder.
    process = subprocess.Popen(["git", "remote", "-v"], stdout=subprocess.PIPE)
    remotes = str(process.stdout.read())
    url = remotes.split(" ", 1)[0]  # gets the fetch url
    url = url.split("\\t", 1)[0]  # takes out extra info
    arguments = url.split(".com/")[1]  # gets just the username/repo.git
    arguments = arguments[:len(arguments) - 4]  # takes out ".git"
    username, repo = arguments.split("/")

    # gets token from config folder.
    try:
        import os
        with open(os.path.expanduser("~/.config/git-hub.yaml")) as stream:
            yaml_file = str(yaml.load(stream))
            token = yaml_file.split("=")[1].strip()

    except (IndexError, FileNotFoundError) as e:
        print(textwrap.dedent("""Needs an authentification token in: ~/.config/git-hub.yaml
            file simply says: token = abc123
            Visit https://help.github.com/articles/
            creating-a-personal-access-token-for-the-command-line/"""))
        sys.exit(1)

    # gets pr and runs command.
    try:
        g = github.Github(token)
        filepath = os.path.join('./.git/', 'pull-requests.toml')
        f = open(filepath, "w")
        to_write = "['open pull requests']\n"   #later will be convereted to toml to store

        #creates dictionaries in toml format as we scan though pull requests
        open_prs = g.get_user(username).get_repo(repo).get_pulls("open")
        for pr in open_prs:
            to_write = to_write + "{0} = '{1}'\n".format(pr.number, pr.title)

        to_write = to_write + "['closed pull requests']\n"
        closed_prs = g.get_user(username).get_repo(repo).get_pulls("closed")
        for pr in closed_prs:
            to_write = to_write + "{0} = '{1}'\n".format(pr.number, pr.title)

        #converts it to toml and stores in file
        toml_string = toml.loads(to_write)
        toml.dump(toml_string, f)


    except github.BadCredentialsException as e:
        print(e)
        print("The authentification token is not valid.")
        sys.exit(1)


@click.group()
def cli():
    pass


@cli.command()
@click.argument("command", default="")
@click.argument("args", nargs=-1)
def hub(command, args):
    if command == "pr":
        pr_num = int(args[0])
        pr(pr_num)

    elif command == "push":
        push()

    elif command == "search":
        params = ' '.join(args)         #concatenates all words as search keywords
        search(params)

    elif command == "sync":
        sync()

    else:
        print("invalid command")
        sys.exit(1)


if __name__ == "__main__":
    hub()
